FROM node:20-slim AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable
WORKDIR /app

FROM base AS build
COPY . /app
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile
ENV NODE_ENV=production
RUN pnpm run -r build

FROM nginx:1.26-alpine-slim AS client
COPY --from=build /app/packages/oapi-todo/dist /usr/share/nginx/html
COPY --from=build /app/packages/oapi-todo/nginx.conf /etc/nginx/conf.d/default.conf
