services:
  server:
    build:
      context: ./go/oapi-todo
      dockerfile: Dockerfile
    ports:
      - "6970:6970"
    volumes:
      - "./go/oapi-todo/db_data:/app/db_data"

  client:
    build:
      context: ./js/
      target: client
      dockerfile: Dockerfile.oapi-todo
    ports:
      - "5174:80"
    depends_on:
      - server
